disqus: dingxuewen
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
gitalk:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner:  ## Your GitHub ID, e.g. username
  repo:  ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id:  ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret:  ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin:  ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-è¯„è®ºç³»ç»Ÿä¸­çš„é‚®ä»¶æé†’è®¾ç½®
  verify: true ## Validation code.
  placeholder: Just so so ## Comment box placeholders.
  avatar: 'mm' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

google_search: true ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: false ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-92630037-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: true ## If you want to use fancybox please set the value to true.
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: false ## If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
donate:
  enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: /img/alipay.jpg ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: /img/wechatpay.jpg ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: LeviDing ## Your author name, e.g. tufu9441
  copyright_text: ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
#  - page: books
#    directory: books/
#    icon: fa-book
#  - page: movies
#    directory: movies/
#    icon: fa-film
  - page: about
    directory: about/
    icon: fa-user
  - page: history
    directory: history/
    icon: fa-history
  - page: guestbook
    directory: guestbook/
    icon: fa-comment
#  - page: algorithm
#    directory: leetcode-js-leviding/
#    icon: fa-rocket
#    target: _blank
  - page: rss
    directory: atom.xml
    icon: fa-rss
    target: _blank

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - projects
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

projects:
  - title: æœ€æ–°æŠ€æœ¯çŸ¥è¯†å’Œè¶£é—»
    url: https://leviding.github.io/technical-talk
  - title: ç°ä»£ JavaScript æ•™ç¨‹
    url: https://zh.javascript.info
  - title: LeetCode JavaScript é¢˜è§£
    url: https://leviding.github.io/leetcode-js-leviding

links:
  - title: LeviDing.com
    url: https://leviding.com
  - title: æˆ‘çš„ã€ŒGitHubã€
    url: https://github.com/leviding
  - title: æˆ‘çš„ã€Œæ˜é‡‘ã€ä¸»é¡µ
    url: https://juejin.im/user/589881b7128fe1006cbbacec/posts
  - title: æˆ‘çš„ã€ŒçŸ¥ä¹ã€ä¸»é¡µ
    url: https://www.zhihu.com/people/leviding
  - title: æˆ‘çš„ã€Œå¾®åšã€ä¸»é¡µ
    url: https://weibo.com/leviding
  - title: æˆ‘çš„ã€Œè±†ç“£ã€ä¸»é¡µ
    url: https://www.douban.com/people/dingxuewen/

timeline:
  - num: 20
    word: ç°åœ¨ï¼ŒèŒåœºæ‰“æ‹¼å­¦ä¹ ä¸­ ğŸ’ª
  - num: 19
    word: 2021 å¹´ 07 æœˆï¼Œç»“æŸåœ¨é˜¿é‡Œå·´å·´-é˜¿é‡Œäº‘(æ­å·)çš„å®ä¹ ï¼Œè½¬ä¸ºæ­£å¼å…¥èŒ
  - num: 18
    word: 2021 å¹´ 06 æœˆä»ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰ç ”ç©¶ç”Ÿæ¯•ä¸šï¼Œè·å·¥å­¦ç¡•å£«å­¦ä½ï¼Œæ ¡ä¼˜ç§€æ¯•ä¸šç”Ÿ
  - num: 17
    word: 2021 å¹´ 01 æœˆå…¥èŒé˜¿é‡Œå·´å·´-é˜¿é‡Œäº‘(æ­å·)å®ä¹ ï¼Œå‰ç«¯å¼€å‘
  - num: 16
    word: 2020 å¹´ 11 æœˆï¼Œå®Œæˆä¸‰æ–¹ç­¾è®¢ï¼Œå°†å…¥èŒé˜¿é‡Œå·´å·´-é˜¿é‡Œäº‘(æ­å·)ã€‚ç§‹æ‹›æœŸé—´é¢è¯•åå®¶å…¬å¸ï¼Œæ‹¿åˆ°é˜¿é‡Œå·´å·´-é˜¿é‡Œäº‘ã€æ‹¼å¤šå¤šã€ç½‘æ˜“ã€äº¬ä¸œã€å¥½æœªæ¥ã€æ–—é±¼ã€é¡ºä¸°å’Œå°é¹æ±½è½¦ 8 ä¸ª offerï¼ŒåŒ…æ‹¬å¤šä¸ª SP
  - num: 15
    word: 2020 å¹´ 08 æœˆï¼Œåœ¨å¢¨åˆ€åŒ—äº¬å®ä¹ ï¼Œå‰ç«¯å¼€å‘ï¼Œä¸ºæœŸä¸€ä¸ªæœˆ
  - num: 14
    word: 2019 å¹´ 07 æœˆï¼Œä»æ˜é‡‘ç¦»èŒï¼Œæ­¤æ®µå·¥ä½œä¸ºæœŸä¸¤å¹´æ•´ã€‚åŒæœˆç»“æŸè‡ªåŠ¨åŒ–å­¦é™¢å…¼èŒè¾…å¯¼å‘˜å·¥ä½œ
  - num: 13
    word: 2018 å¹´ 09 æœˆï¼Œä¿é€è‡³ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰æ§åˆ¶å­¦ç§‘ä¸å·¥ç¨‹ä¸“ä¸šæ”»è¯»ç¡•å£«å­¦ä½ï¼Œå¸ˆä»â€œé•¿æ±Ÿå­¦è€…â€ä½•å‹‡æ•™æˆã€‚åŒæœˆå—è˜æ‹…ä»»è‡ªåŠ¨åŒ–å­¦é™¢å…¼èŒè¾…å¯¼å‘˜ï¼Œä»»æœŸä¸€å¹´ï¼Œè´Ÿè´£ç ”ç©¶ç”Ÿç®¡ç†å·¥ä½œ
  - num: 12
    word: 2018 å¹´ 06 æœˆï¼Œä»ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰æœ¬ç§‘æ¯•ä¸šï¼Œè·å·¥å­¦å­¦å£«å­¦ä½
  - num: 11
    word: 2018 å¹´ 05 æœˆï¼Œå®Œæˆäº†æœ¬ç§‘æ¯•ä¸šè®ºæ–‡ã€ŠåŸºäºé›†æˆå­¦ä¹ çš„è„‘ç”µæƒ…æ„Ÿè¯†åˆ«æ–¹æ³•ç ”ç©¶ã€‹ï¼Œå¹¶è·å¾—æ ¡çº§ä¼˜ç§€æ¯•ä¸šè®ºæ–‡ï¼Œè·è¯„æ¯”ä¾‹ 5%
  - num: 10
    word: 2018 å¹´ 04 æœˆï¼Œä»» The Modern JavaScript Tutorial ä¸­å›½è´Ÿè´£äºº 
  - num: 9
    word: 2017 å¹´ 12 æœˆï¼Œç»“æŸåœ¨æ˜é‡‘çš„å®ä¹ å·¥ä½œï¼Œè½¬ä¸ºè¿œç¨‹å…¼èŒå·¥ä½œï¼Œæ­¤æ®µå®ä¹ ä¸ºæœŸå››ä¸ªæœˆ
  - num: 8
    word: 2017 å¹´ 10 æœˆï¼Œå…¨é¢å¥–å­¦é‡‘èµ´æ—¥æœ¬ä¸œäº¬å·¥ç§‘å¤§å­¦è¿›è¡ŒçŸ­æœŸè®¿å­¦
  - num: 7
    word: 2017 å¹´ 08 æœˆï¼Œåœ¨æ˜é‡‘åŒ—äº¬å®ä¹ ï¼Œå…¨æƒè´Ÿè´£æ˜é‡‘ç¿»è¯‘è®¡åˆ’
  - num: 6
    word: 2015 å¹´ 11 æœˆï¼Œå…¥é€‰ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰ç§‘å­¦å®¶è®¡åˆ’ï¼Œå…¥é€‰æ¯”ä¾‹ 60/9000
  - num: 5
    word: 2015 å¹´ 06 æœˆï¼Œå…¥é€‰ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰æå››å…‰è®¡åˆ’ï¼Œå…¥é€‰æ¯”ä¾‹ 30/4500
  - num: 4
    word: 2014 å¹´ 09 æœˆï¼Œé«˜è€ƒè€ƒå…¥ä¸­å›½åœ°è´¨å¤§å­¦ï¼ˆæ­¦æ±‰ï¼‰æµ‹æ§æŠ€æœ¯ä¸ä»ªå™¨ä¸“ä¸š
  - num: 3
    word: 2011 å¹´ 09 æœˆï¼Œä¸­è€ƒè€ƒå…¥å‰æ—çœå»¶è¾¹ç¬¬äºŒä¸­å­¦
  - num: 2
    word: 2008 å¹´ 09 æœˆï¼Œå°å‡åˆè€ƒå…¥å‰æ—çœå»¶è¾¹ç¬¬ä¸‰ä¸­å­¦
  - num: 1
    word: 1995 å¹´ 05 æœˆï¼Œæˆ‘å‡ºç”Ÿåœ¨å‰æ—å»¶è¾¹

# Static files
js: js
css: css

# Theme version
version: 0.0.0
